# Generated by Django 6.0.4 on 2026-04-13 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_complaint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={},
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='description',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
